### ISSUE TITLE
Unsustainable dependency graph

### ISSUE THREAD

**Issue by toqueteos** [shurcooL/Conception-go#8]
Take a look at http://godoc.org/github.com/shurcooL/Conception-go?import-graph&hide=2

All those gists *made repos* are not gonna work in the future.

**Comment by shurcooL** [comment]
Yes, Conception-go has a large number of dependencies. That is expected because its scope is quite large.

I am actively maintaining and watching all of the dependencies. The Travis build ensures the project builds with latest versions. If there's ever a problem upstream, I fix it quickly. So I don't think it's a problem.

As far as Go packages with "gist" in the name, they're all contained in a single git repo that I host, so they're only going away when they're no longer needed, not sooner. See https://github.com/shurcooL/go/tree/master/gists. I've been slowly refactoring my code to move those packages so they have a better import path, or deleting unneeded ones. For example, see https://github.com/shurcooL/go/commit/6a87214792d61acab97453570733996a1ee4f4c8.

**Comment by toqueteos** [comment]
That's good to know. I just saw the repo and I always tend to check the dependency graph first and was.. astonished.

If refactoring is in progress then there's nothing to worry. Closing issue.
